# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stellate.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 964)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1600, 900))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabViewer = QtWidgets.QWidget()
        self.tabViewer.setObjectName("tabViewer")
        self.imgViewer = QtWidgets.QGraphicsView(self.tabViewer)
        self.imgViewer.setGeometry(QtCore.QRect(10, 10, 1441, 851))
        self.imgViewer.setMinimumSize(QtCore.QSize(128, 128))
        self.imgViewer.setMouseTracking(True)
        self.imgViewer.setLineWidth(2)
        self.imgViewer.setObjectName("imgViewer")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabViewer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1460, 10, 121, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.imgButtonLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.imgButtonLayout.setContentsMargins(0, 0, 0, 0)
        self.imgButtonLayout.setObjectName("imgButtonLayout")
        self.autoStretchButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoStretchButton.sizePolicy().hasHeightForWidth())
        self.autoStretchButton.setSizePolicy(sizePolicy)
        self.autoStretchButton.setCheckable(True)
        self.autoStretchButton.setDefault(False)
        self.autoStretchButton.setFlat(False)
        self.autoStretchButton.setObjectName("autoStretchButton")
        self.imgButtonLayout.addWidget(self.autoStretchButton)
        self.luminanceButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.luminanceButton.sizePolicy().hasHeightForWidth())
        self.luminanceButton.setSizePolicy(sizePolicy)
        self.luminanceButton.setCheckable(True)
        self.luminanceButton.setDefault(False)
        self.luminanceButton.setFlat(False)
        self.luminanceButton.setObjectName("luminanceButton")
        self.imgButtonLayout.addWidget(self.luminanceButton)
        self.redButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redButton.sizePolicy().hasHeightForWidth())
        self.redButton.setSizePolicy(sizePolicy)
        self.redButton.setCheckable(True)
        self.redButton.setDefault(False)
        self.redButton.setFlat(False)
        self.redButton.setObjectName("redButton")
        self.imgButtonLayout.addWidget(self.redButton)
        self.greenButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenButton.sizePolicy().hasHeightForWidth())
        self.greenButton.setSizePolicy(sizePolicy)
        self.greenButton.setCheckable(True)
        self.greenButton.setDefault(False)
        self.greenButton.setFlat(False)
        self.greenButton.setObjectName("greenButton")
        self.imgButtonLayout.addWidget(self.greenButton)
        self.blueButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blueButton.sizePolicy().hasHeightForWidth())
        self.blueButton.setSizePolicy(sizePolicy)
        self.blueButton.setCheckable(True)
        self.blueButton.setDefault(False)
        self.blueButton.setFlat(False)
        self.blueButton.setObjectName("blueButton")
        self.imgButtonLayout.addWidget(self.blueButton)
        self.tabWidget.addTab(self.tabViewer, "")
        self.tabStacker = QtWidgets.QWidget()
        self.tabStacker.setObjectName("tabStacker")
        self.tabWidget.addTab(self.tabStacker, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_FITS = QtWidgets.QAction(MainWindow)
        self.actionSave_FITS.setObjectName("actionSave_FITS")
        self.actionOpen_FITS = QtWidgets.QAction(MainWindow)
        self.actionOpen_FITS.setObjectName("actionOpen_FITS")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionOpen_FITS)
        self.menuFile.addAction(self.actionSave_FITS)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionClose.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.autoStretchButton.setText(_translate("MainWindow", "Auto Stretch"))
        self.luminanceButton.setText(_translate("MainWindow", "Luminance"))
        self.redButton.setText(_translate("MainWindow", "Red"))
        self.greenButton.setText(_translate("MainWindow", "Green"))
        self.blueButton.setText(_translate("MainWindow", "Blue"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabViewer), _translate("MainWindow", "Viewer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStacker), _translate("MainWindow", "Stacker"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_FITS.setText(_translate("MainWindow", "Save FITS ..."))
        self.actionSave_FITS.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen_FITS.setText(_translate("MainWindow", "Open FITS ..."))
        self.actionOpen_FITS.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))

