# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stellate.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1259, 752)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1140, 680))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(512, 512))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabView = QtWidgets.QWidget()
        self.tabView.setObjectName("tabView")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.viewer = imgViewer(self.tabView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer.sizePolicy().hasHeightForWidth())
        self.viewer.setSizePolicy(sizePolicy)
        self.viewer.setMinimumSize(QtCore.QSize(256, 256))
        self.viewer.setMouseTracking(True)
        self.viewer.setLineWidth(2)
        self.viewer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.viewer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.viewer.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.viewer.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.viewer.setObjectName("viewer")
        self.horizontalLayout.addWidget(self.viewer)
        self.widget_2 = QtWidgets.QWidget(self.tabView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.channelsGroupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelsGroupBox.sizePolicy().hasHeightForWidth())
        self.channelsGroupBox.setSizePolicy(sizePolicy)
        self.channelsGroupBox.setMinimumSize(QtCore.QSize(256, 64))
        self.channelsGroupBox.setMaximumSize(QtCore.QSize(16777215, 64))
        self.channelsGroupBox.setObjectName("channelsGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.channelsGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.luminanceButton = QtWidgets.QPushButton(self.channelsGroupBox)
        self.luminanceButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.luminanceButton.sizePolicy().hasHeightForWidth())
        self.luminanceButton.setSizePolicy(sizePolicy)
        self.luminanceButton.setMinimumSize(QtCore.QSize(0, 0))
        self.luminanceButton.setCheckable(True)
        self.luminanceButton.setDefault(False)
        self.luminanceButton.setFlat(False)
        self.luminanceButton.setObjectName("luminanceButton")
        self.horizontalLayout_2.addWidget(self.luminanceButton)
        self.redButton = QtWidgets.QPushButton(self.channelsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redButton.sizePolicy().hasHeightForWidth())
        self.redButton.setSizePolicy(sizePolicy)
        self.redButton.setMinimumSize(QtCore.QSize(0, 0))
        self.redButton.setCheckable(True)
        self.redButton.setDefault(False)
        self.redButton.setFlat(False)
        self.redButton.setObjectName("redButton")
        self.horizontalLayout_2.addWidget(self.redButton)
        self.greenButton = QtWidgets.QPushButton(self.channelsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenButton.sizePolicy().hasHeightForWidth())
        self.greenButton.setSizePolicy(sizePolicy)
        self.greenButton.setMinimumSize(QtCore.QSize(0, 0))
        self.greenButton.setCheckable(True)
        self.greenButton.setDefault(False)
        self.greenButton.setFlat(False)
        self.greenButton.setObjectName("greenButton")
        self.horizontalLayout_2.addWidget(self.greenButton)
        self.blueButton = QtWidgets.QPushButton(self.channelsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blueButton.sizePolicy().hasHeightForWidth())
        self.blueButton.setSizePolicy(sizePolicy)
        self.blueButton.setMinimumSize(QtCore.QSize(0, 0))
        self.blueButton.setCheckable(True)
        self.blueButton.setDefault(False)
        self.blueButton.setFlat(False)
        self.blueButton.setObjectName("blueButton")
        self.horizontalLayout_2.addWidget(self.blueButton)
        self.verticalLayout.addWidget(self.channelsGroupBox)
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(256, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(256, 64))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 64))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.imax = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imax.sizePolicy().hasHeightForWidth())
        self.imax.setSizePolicy(sizePolicy)
        self.imax.setMinimumSize(QtCore.QSize(0, 20))
        self.imax.setAlignment(QtCore.Qt.AlignCenter)
        self.imax.setObjectName("imax")
        self.gridLayout.addWidget(self.imax, 0, 2, 1, 1)
        self.pmax = QtWidgets.QLineEdit(self.widget)
        self.pmax.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pmax.sizePolicy().hasHeightForWidth())
        self.pmax.setSizePolicy(sizePolicy)
        self.pmax.setMinimumSize(QtCore.QSize(0, 20))
        self.pmax.setAlignment(QtCore.Qt.AlignCenter)
        self.pmax.setObjectName("pmax")
        self.gridLayout.addWidget(self.pmax, 1, 2, 1, 1)
        self.imin = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imin.sizePolicy().hasHeightForWidth())
        self.imin.setSizePolicy(sizePolicy)
        self.imin.setMinimumSize(QtCore.QSize(0, 20))
        self.imin.setAlignment(QtCore.Qt.AlignCenter)
        self.imin.setObjectName("imin")
        self.gridLayout.addWidget(self.imin, 0, 1, 1, 1)
        self.pmin = QtWidgets.QLineEdit(self.widget)
        self.pmin.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pmin.sizePolicy().hasHeightForWidth())
        self.pmin.setSizePolicy(sizePolicy)
        self.pmin.setMinimumSize(QtCore.QSize(0, 20))
        self.pmin.setAlignment(QtCore.Qt.AlignCenter)
        self.pmin.setObjectName("pmin")
        self.gridLayout.addWidget(self.pmin, 1, 1, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 1, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(320, 128))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_4.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.infoGroupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoGroupBox.sizePolicy().hasHeightForWidth())
        self.infoGroupBox.setSizePolicy(sizePolicy)
        self.infoGroupBox.setMinimumSize(QtCore.QSize(0, 256))
        self.infoGroupBox.setObjectName("infoGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.infoGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.infoGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setDocumentTitle("")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.verticalLayout.addWidget(self.infoGroupBox)
        self.horizontalLayout.addWidget(self.widget_2)
        self.tabWidget.addTab(self.tabView, "")
        self.tabRegister = QtWidgets.QWidget()
        self.tabRegister.setObjectName("tabRegister")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabRegister)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabRegister)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 64))
        self.groupBox_2.setObjectName("groupBox_2")
        self.findStarsButton = QtWidgets.QPushButton(self.groupBox_2)
        self.findStarsButton.setGeometry(QtCore.QRect(10, 25, 104, 32))
        self.findStarsButton.setObjectName("findStarsButton")
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.registerImageList = QtWidgets.QTableWidget(self.tabRegister)
        self.registerImageList.setFrameShape(QtWidgets.QFrame.Panel)
        self.registerImageList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.registerImageList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.registerImageList.setAlternatingRowColors(True)
        self.registerImageList.setIconSize(QtCore.QSize(0, 0))
        self.registerImageList.setGridStyle(QtCore.Qt.DotLine)
        self.registerImageList.setWordWrap(True)
        self.registerImageList.setRowCount(10)
        self.registerImageList.setColumnCount(5)
        self.registerImageList.setObjectName("registerImageList")
        item = QtWidgets.QTableWidgetItem()
        self.registerImageList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerImageList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerImageList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerImageList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerImageList.setHorizontalHeaderItem(4, item)
        self.registerImageList.horizontalHeader().setDefaultSectionSize(128)
        self.registerImageList.horizontalHeader().setMinimumSectionSize(64)
        self.registerImageList.horizontalHeader().setStretchLastSection(True)
        self.registerImageList.verticalHeader().setCascadingSectionResizes(False)
        self.registerImageList.verticalHeader().setMinimumSectionSize(20)
        self.registerImageList.verticalHeader().setSortIndicatorShown(True)
        self.registerImageList.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.registerImageList)
        self.tabWidget.addTab(self.tabRegister, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1259, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_FITS = QtWidgets.QAction(MainWindow)
        self.actionSave_FITS.setObjectName("actionSave_FITS")
        self.actionOpen_FITS = QtWidgets.QAction(MainWindow)
        self.actionOpen_FITS.setObjectName("actionOpen_FITS")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionFindStars = QtWidgets.QAction(MainWindow)
        self.actionFindStars.setObjectName("actionFindStars")
        self.actionLinearScale = QtWidgets.QAction(MainWindow)
        self.actionLinearScale.setObjectName("actionLinearScale")
        self.actionPercentileScale = QtWidgets.QAction(MainWindow)
        self.actionPercentileScale.setObjectName("actionPercentileScale")
        self.menuFile.addAction(self.actionOpen_FITS)
        self.menuFile.addAction(self.actionSave_FITS)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.actionClose.triggered.connect(MainWindow.close)
        self.findStarsButton.pressed.connect(self.actionFindStars.trigger)
        self.radioButton.clicked.connect(self.actionLinearScale.trigger)
        self.radioButton_2.pressed.connect(self.actionPercentileScale.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.viewer.setToolTip(_translate("MainWindow", "FITS image view. Left mouse button pans, mouse wheel zooms."))
        self.channelsGroupBox.setTitle(_translate("MainWindow", "Channels"))
        self.luminanceButton.setText(_translate("MainWindow", "Luminance"))
        self.redButton.setText(_translate("MainWindow", "Red"))
        self.greenButton.setText(_translate("MainWindow", "Green"))
        self.blueButton.setText(_translate("MainWindow", "Blue"))
        self.groupBox.setTitle(_translate("MainWindow", "Intensity Scaling"))
        self.imax.setText(_translate("MainWindow", "16384"))
        self.pmax.setText(_translate("MainWindow", "95"))
        self.imin.setText(_translate("MainWindow", "0"))
        self.pmin.setText(_translate("MainWindow", "5"))
        self.radioButton.setText(_translate("MainWindow", "Linear"))
        self.radioButton_2.setText(_translate("MainWindow", "Percentile"))
        self.infoGroupBox.setTitle(_translate("MainWindow", "Image Information"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Double click to recalculate image statistics."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabView), _translate("MainWindow", "View"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Object Detection"))
        self.findStarsButton.setText(_translate("MainWindow", "Find Stars"))
        self.registerImageList.setSortingEnabled(True)
        item = self.registerImageList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X Disp"))
        item = self.registerImageList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y Disp"))
        item = self.registerImageList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rotation"))
        item = self.registerImageList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "FWHM"))
        item = self.registerImageList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Image File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRegister), _translate("MainWindow", "Register"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Deconv"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_FITS.setText(_translate("MainWindow", "Save FITS ..."))
        self.actionSave_FITS.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen_FITS.setText(_translate("MainWindow", "Open FITS ..."))
        self.actionOpen_FITS.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionFindStars.setText(_translate("MainWindow", "FindStars"))
        self.actionFindStars.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionLinearScale.setText(_translate("MainWindow", "LinearScale"))
        self.actionPercentileScale.setText(_translate("MainWindow", "PercentileScale"))

from imgviewer import imgViewer
