# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stellate.ui',
# licensing of 'stellate.ui' applies.
#
# Created: Wed Mar 13 15:37:56 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1177, 776)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 24))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 45))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.fnameText = QtWidgets.QLineEdit(self.widget)
        self.fnameText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fnameText.setReadOnly(True)
        self.fnameText.setPlaceholderText("")
        self.fnameText.setObjectName("fnameText")
        self.horizontalLayout_5.addWidget(self.fnameText)
        self.indexLabel = QtWidgets.QLabel(self.widget)
        self.indexLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.indexLabel.setObjectName("indexLabel")
        self.horizontalLayout_5.addWidget(self.indexLabel)
        self.indexText = QtWidgets.QLineEdit(self.widget)
        self.indexText.setMaximumSize(QtCore.QSize(60, 16777215))
        self.indexText.setAlignment(QtCore.Qt.AlignCenter)
        self.indexText.setReadOnly(False)
        self.indexText.setObjectName("indexText")
        self.horizontalLayout_5.addWidget(self.indexText)
        self.ofLabel = QtWidgets.QLabel(self.widget)
        self.ofLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ofLabel.setObjectName("ofLabel")
        self.horizontalLayout_5.addWidget(self.ofLabel)
        self.maxIndexText = QtWidgets.QLineEdit(self.widget)
        self.maxIndexText.setMaximumSize(QtCore.QSize(60, 16777215))
        self.maxIndexText.setFrame(False)
        self.maxIndexText.setAlignment(QtCore.Qt.AlignCenter)
        self.maxIndexText.setReadOnly(True)
        self.maxIndexText.setObjectName("maxIndexText")
        self.horizontalLayout_5.addWidget(self.maxIndexText)
        self.verticalLayout_2.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabView = QtWidgets.QWidget()
        self.tabView.setObjectName("tabView")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StackTools = QtWidgets.QToolBox(self.tabView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackTools.sizePolicy().hasHeightForWidth())
        self.StackTools.setSizePolicy(sizePolicy)
        self.StackTools.setMinimumSize(QtCore.QSize(200, 400))
        self.StackTools.setMaximumSize(QtCore.QSize(200, 16777215))
        self.StackTools.setAutoFillBackground(False)
        self.StackTools.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.StackTools.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.StackTools.setLineWidth(1)
        self.StackTools.setMidLineWidth(0)
        self.StackTools.setObjectName("StackTools")
        self.levelsTools = QtWidgets.QWidget()
        self.levelsTools.setGeometry(QtCore.QRect(0, 0, 200, 499))
        self.levelsTools.setObjectName("levelsTools")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.levelsTools)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.maxLevelSlider = QtWidgets.QSlider(self.levelsTools)
        self.maxLevelSlider.setMaximum(100)
        self.maxLevelSlider.setProperty("value", 100)
        self.maxLevelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.maxLevelSlider.setObjectName("maxLevelSlider")
        self.verticalLayout_5.addWidget(self.maxLevelSlider)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minLevelText = QtWidgets.QLineEdit(self.levelsTools)
        self.minLevelText.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.minLevelText.setAlignment(QtCore.Qt.AlignCenter)
        self.minLevelText.setObjectName("minLevelText")
        self.horizontalLayout_2.addWidget(self.minLevelText)
        self.maxLevelText = QtWidgets.QLineEdit(self.levelsTools)
        self.maxLevelText.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.maxLevelText.setAlignment(QtCore.Qt.AlignCenter)
        self.maxLevelText.setObjectName("maxLevelText")
        self.horizontalLayout_2.addWidget(self.maxLevelText)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.minLevelSlider = QtWidgets.QSlider(self.levelsTools)
        self.minLevelSlider.setMaximum(100)
        self.minLevelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minLevelSlider.setObjectName("minLevelSlider")
        self.verticalLayout_5.addWidget(self.minLevelSlider)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.StackTools.addItem(self.levelsTools, "")
        self.starsTools = QtWidgets.QWidget()
        self.starsTools.setGeometry(QtCore.QRect(0, 0, 116, 62))
        self.starsTools.setObjectName("starsTools")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.starsTools)
        self.verticalLayout.setObjectName("verticalLayout")
        self.findStarsButton = QtWidgets.QPushButton(self.starsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findStarsButton.sizePolicy().hasHeightForWidth())
        self.findStarsButton.setSizePolicy(sizePolicy)
        self.findStarsButton.setMinimumSize(QtCore.QSize(0, 40))
        self.findStarsButton.setMaximumSize(QtCore.QSize(1000, 40))
        self.findStarsButton.setObjectName("findStarsButton")
        self.verticalLayout.addWidget(self.findStarsButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 398, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.StackTools.addItem(self.starsTools, "")
        self.registerTools = QtWidgets.QWidget()
        self.registerTools.setGeometry(QtCore.QRect(0, 0, 193, 262))
        self.registerTools.setObjectName("registerTools")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.registerTools)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.registerStackButton = QtWidgets.QPushButton(self.registerTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerStackButton.sizePolicy().hasHeightForWidth())
        self.registerStackButton.setSizePolicy(sizePolicy)
        self.registerStackButton.setMinimumSize(QtCore.QSize(175, 40))
        self.registerStackButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.registerStackButton.setObjectName("registerStackButton")
        self.verticalLayout_6.addWidget(self.registerStackButton)
        self.averageStackButton = QtWidgets.QPushButton(self.registerTools)
        self.averageStackButton.setMinimumSize(QtCore.QSize(175, 40))
        self.averageStackButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.averageStackButton.setCheckable(False)
        self.averageStackButton.setObjectName("averageStackButton")
        self.verticalLayout_6.addWidget(self.averageStackButton)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.refIndexLabel = QtWidgets.QLabel(self.registerTools)
        self.refIndexLabel.setObjectName("refIndexLabel")
        self.horizontalLayout_4.addWidget(self.refIndexLabel)
        self.refIndexText = QtWidgets.QLineEdit(self.registerTools)
        self.refIndexText.setText("")
        self.refIndexText.setAlignment(QtCore.Qt.AlignCenter)
        self.refIndexText.setReadOnly(False)
        self.refIndexText.setObjectName("refIndexText")
        self.horizontalLayout_4.addWidget(self.refIndexText)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.misregModelChoice = QtWidgets.QComboBox(self.registerTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.misregModelChoice.sizePolicy().hasHeightForWidth())
        self.misregModelChoice.setSizePolicy(sizePolicy)
        self.misregModelChoice.setMinimumSize(QtCore.QSize(175, 0))
        self.misregModelChoice.setMaximumSize(QtCore.QSize(200, 16777215))
        self.misregModelChoice.setObjectName("misregModelChoice")
        self.misregModelChoice.addItem("")
        self.misregModelChoice.addItem("")
        self.misregModelChoice.addItem("")
        self.verticalLayout_6.addWidget(self.misregModelChoice)
        self.combMethodChoice = QtWidgets.QComboBox(self.registerTools)
        self.combMethodChoice.setMinimumSize(QtCore.QSize(175, 0))
        self.combMethodChoice.setMaximumSize(QtCore.QSize(200, 16777215))
        self.combMethodChoice.setObjectName("combMethodChoice")
        self.combMethodChoice.addItem("")
        self.combMethodChoice.addItem("")
        self.combMethodChoice.addItem("")
        self.verticalLayout_6.addWidget(self.combMethodChoice)
        self.checkBox = QtWidgets.QCheckBox(self.registerTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setMinimumSize(QtCore.QSize(175, 0))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(self.checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 398, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.registerProgressBar = QtWidgets.QProgressBar(self.registerTools)
        self.registerProgressBar.setProperty("value", 0)
        self.registerProgressBar.setInvertedAppearance(False)
        self.registerProgressBar.setObjectName("registerProgressBar")
        self.verticalLayout_6.addWidget(self.registerProgressBar)
        self.StackTools.addItem(self.registerTools, "")
        self.horizontalLayout.addWidget(self.StackTools)
        self.StackViewer = ImageViewer(self.tabView)
        self.StackViewer.setMinimumSize(QtCore.QSize(400, 400))
        self.StackViewer.setObjectName("StackViewer")
        self.horizontalLayout.addWidget(self.StackViewer)
        self.tabWidget.addTab(self.tabView, "")
        self.tabLRGB = QtWidgets.QWidget()
        self.tabLRGB.setObjectName("tabLRGB")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tabLRGB)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_2 = QtWidgets.QWidget(self.tabLRGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(160, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.loadRedButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadRedButton.sizePolicy().hasHeightForWidth())
        self.loadRedButton.setSizePolicy(sizePolicy)
        self.loadRedButton.setMinimumSize(QtCore.QSize(40, 40))
        self.loadRedButton.setMaximumSize(QtCore.QSize(40, 40))
        self.loadRedButton.setObjectName("loadRedButton")
        self.gridLayout.addWidget(self.loadRedButton, 0, 2, 1, 1)
        self.loadBlueButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadBlueButton.sizePolicy().hasHeightForWidth())
        self.loadBlueButton.setSizePolicy(sizePolicy)
        self.loadBlueButton.setMinimumSize(QtCore.QSize(40, 40))
        self.loadBlueButton.setMaximumSize(QtCore.QSize(40, 40))
        self.loadBlueButton.setObjectName("loadBlueButton")
        self.gridLayout.addWidget(self.loadBlueButton, 0, 4, 1, 1)
        self.loadGreenButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadGreenButton.sizePolicy().hasHeightForWidth())
        self.loadGreenButton.setSizePolicy(sizePolicy)
        self.loadGreenButton.setMinimumSize(QtCore.QSize(40, 40))
        self.loadGreenButton.setMaximumSize(QtCore.QSize(40, 40))
        self.loadGreenButton.setObjectName("loadGreenButton")
        self.gridLayout.addWidget(self.loadGreenButton, 0, 3, 1, 1)
        self.loadLumButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadLumButton.sizePolicy().hasHeightForWidth())
        self.loadLumButton.setSizePolicy(sizePolicy)
        self.loadLumButton.setMinimumSize(QtCore.QSize(40, 40))
        self.loadLumButton.setMaximumSize(QtCore.QSize(40, 40))
        self.loadLumButton.setObjectName("loadLumButton")
        self.gridLayout.addWidget(self.loadLumButton, 0, 1, 1, 1)
        self.lumSlider = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lumSlider.sizePolicy().hasHeightForWidth())
        self.lumSlider.setSizePolicy(sizePolicy)
        self.lumSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.lumSlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lumSlider.setMaximum(100)
        self.lumSlider.setProperty("value", 100)
        self.lumSlider.setOrientation(QtCore.Qt.Vertical)
        self.lumSlider.setObjectName("lumSlider")
        self.gridLayout.addWidget(self.lumSlider, 1, 1, 1, 1)
        self.redSlider = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redSlider.sizePolicy().hasHeightForWidth())
        self.redSlider.setSizePolicy(sizePolicy)
        self.redSlider.setMaximum(100)
        self.redSlider.setProperty("value", 100)
        self.redSlider.setOrientation(QtCore.Qt.Vertical)
        self.redSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.redSlider.setTickInterval(25)
        self.redSlider.setObjectName("redSlider")
        self.gridLayout.addWidget(self.redSlider, 1, 2, 1, 1)
        self.greenSlider = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenSlider.sizePolicy().hasHeightForWidth())
        self.greenSlider.setSizePolicy(sizePolicy)
        self.greenSlider.setMaximum(100)
        self.greenSlider.setProperty("value", 100)
        self.greenSlider.setOrientation(QtCore.Qt.Vertical)
        self.greenSlider.setObjectName("greenSlider")
        self.gridLayout.addWidget(self.greenSlider, 1, 3, 1, 1)
        self.blueSlider = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blueSlider.sizePolicy().hasHeightForWidth())
        self.blueSlider.setSizePolicy(sizePolicy)
        self.blueSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.blueSlider.setMaximum(100)
        self.blueSlider.setProperty("value", 100)
        self.blueSlider.setOrientation(QtCore.Qt.Vertical)
        self.blueSlider.setObjectName("blueSlider")
        self.gridLayout.addWidget(self.blueSlider, 1, 4, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_8.addWidget(self.widget_2)
        self.LRGBViewer = ImageViewer(self.tabLRGB)
        self.LRGBViewer.setMinimumSize(QtCore.QSize(400, 400))
        self.LRGBViewer.setObjectName("LRGBViewer")
        self.horizontalLayout_8.addWidget(self.LRGBViewer)
        self.tabWidget.addTab(self.tabLRGB, "")
        self.tabRegistration = QtWidgets.QWidget()
        self.tabRegistration.setObjectName("tabRegistration")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabRegistration)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tabRegistration)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(4, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.maxAvgDiamLabel = QtWidgets.QLabel(self.groupBox)
        self.maxAvgDiamLabel.setObjectName("maxAvgDiamLabel")
        self.horizontalLayout_3.addWidget(self.maxAvgDiamLabel)
        self.maxAvgDiamText = QtWidgets.QLineEdit(self.groupBox)
        self.maxAvgDiamText.setMaximumSize(QtCore.QSize(75, 16777215))
        self.maxAvgDiamText.setAlignment(QtCore.Qt.AlignCenter)
        self.maxAvgDiamText.setObjectName("maxAvgDiamText")
        self.horizontalLayout_3.addWidget(self.maxAvgDiamText)
        self.minAvgCircLabel = QtWidgets.QLabel(self.groupBox)
        self.minAvgCircLabel.setObjectName("minAvgCircLabel")
        self.horizontalLayout_3.addWidget(self.minAvgCircLabel)
        self.minAvgCircText = QtWidgets.QLineEdit(self.groupBox)
        self.minAvgCircText.setMaximumSize(QtCore.QSize(75, 16777215))
        self.minAvgCircText.setAlignment(QtCore.Qt.AlignCenter)
        self.minAvgCircText.setObjectName("minAvgCircText")
        self.horizontalLayout_3.addWidget(self.minAvgCircText)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.registrationTable = QtWidgets.QTableWidget(self.tabRegistration)
        self.registrationTable.setFrameShape(QtWidgets.QFrame.Panel)
        self.registrationTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.registrationTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.registrationTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.registrationTable.setAlternatingRowColors(False)
        self.registrationTable.setIconSize(QtCore.QSize(0, 0))
        self.registrationTable.setGridStyle(QtCore.Qt.DotLine)
        self.registrationTable.setWordWrap(True)
        self.registrationTable.setRowCount(0)
        self.registrationTable.setColumnCount(7)
        self.registrationTable.setObjectName("registrationTable")
        self.registrationTable.setColumnCount(7)
        self.registrationTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(6, item)
        self.registrationTable.horizontalHeader().setDefaultSectionSize(80)
        self.registrationTable.horizontalHeader().setMinimumSectionSize(64)
        self.registrationTable.horizontalHeader().setStretchLastSection(True)
        self.registrationTable.verticalHeader().setCascadingSectionResizes(False)
        self.registrationTable.verticalHeader().setDefaultSectionSize(24)
        self.registrationTable.verticalHeader().setMinimumSectionSize(20)
        self.registrationTable.verticalHeader().setSortIndicatorShown(True)
        self.registrationTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.registrationTable)
        self.tabWidget.addTab(self.tabRegistration, "")
        self.tabMetadata = QtWidgets.QWidget()
        self.tabMetadata.setObjectName("tabMetadata")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabMetadata)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.FITSMetaText = FITSMetaText(self.tabMetadata)
        self.FITSMetaText.setObjectName("FITSMetaText")
        self.verticalLayout_7.addWidget(self.FITSMetaText)
        self.tabWidget.addTab(self.tabMetadata, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1177, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_FITS = QtWidgets.QAction(MainWindow)
        self.actionSave_FITS.setObjectName("actionSave_FITS")
        self.actionOpen_FITS = QtWidgets.QAction(MainWindow)
        self.actionOpen_FITS.setObjectName("actionOpen_FITS")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionFindStars = QtWidgets.QAction(MainWindow)
        self.actionFindStars.setObjectName("actionFindStars")
        self.actionRegisterStack = QtWidgets.QAction(MainWindow)
        self.actionRegisterStack.setObjectName("actionRegisterStack")
        self.actionAverageStack = QtWidgets.QAction(MainWindow)
        self.actionAverageStack.setObjectName("actionAverageStack")
        self.actionRefIndex = QtWidgets.QAction(MainWindow)
        self.actionRefIndex.setObjectName("actionRefIndex")
        self.actionImageIndex = QtWidgets.QAction(MainWindow)
        self.actionImageIndex.setObjectName("actionImageIndex")
        self.actionMaxDiam = QtWidgets.QAction(MainWindow)
        self.actionMaxDiam.setObjectName("actionMaxDiam")
        self.actionMinCirc = QtWidgets.QAction(MainWindow)
        self.actionMinCirc.setObjectName("actionMinCirc")
        self.actionStackLevels = QtWidgets.QAction(MainWindow)
        self.actionStackLevels.setObjectName("actionStackLevels")
        self.menuFile.addAction(self.actionOpen_FITS)
        self.menuFile.addAction(self.actionSave_FITS)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.StackTools.setCurrentIndex(0)
        self.misregModelChoice.setCurrentIndex(1)
        self.combMethodChoice.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.indexText, QtCore.SIGNAL("returnPressed()"), self.actionImageIndex.trigger)
        QtCore.QObject.connect(self.maxAvgDiamText, QtCore.SIGNAL("returnPressed()"), self.actionMaxDiam.trigger)
        QtCore.QObject.connect(self.minAvgCircText, QtCore.SIGNAL("returnPressed()"), self.actionMinCirc.trigger)
        QtCore.QObject.connect(self.registerStackButton, QtCore.SIGNAL("clicked()"), self.actionRegisterStack.trigger)
        QtCore.QObject.connect(self.averageStackButton, QtCore.SIGNAL("clicked()"), self.actionAverageStack.trigger)
        QtCore.QObject.connect(self.findStarsButton, QtCore.SIGNAL("clicked()"), self.actionFindStars.trigger)
        QtCore.QObject.connect(self.refIndexText, QtCore.SIGNAL("returnPressed()"), self.actionRefIndex.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Image File", None, -1))
        self.fnameText.setText(QtWidgets.QApplication.translate("MainWindow", "No Image Loaded", None, -1))
        self.indexLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Index", None, -1))
        self.indexText.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.ofLabel.setText(QtWidgets.QApplication.translate("MainWindow", "of", None, -1))
        self.maxIndexText.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.minLevelText.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.maxLevelText.setText(QtWidgets.QApplication.translate("MainWindow", "100", None, -1))
        self.StackTools.setItemText(self.StackTools.indexOf(self.levelsTools), QtWidgets.QApplication.translate("MainWindow", "Levels", None, -1))
        self.findStarsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Find Stars", None, -1))
        self.StackTools.setItemText(self.StackTools.indexOf(self.starsTools), QtWidgets.QApplication.translate("MainWindow", "Stars", None, -1))
        self.registerStackButton.setText(QtWidgets.QApplication.translate("MainWindow", "Register Stack", None, -1))
        self.averageStackButton.setText(QtWidgets.QApplication.translate("MainWindow", "Combine Stack", None, -1))
        self.refIndexLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Reference Index", None, -1))
        self.misregModelChoice.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Rigid Body", None, -1))
        self.misregModelChoice.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Affine", None, -1))
        self.misregModelChoice.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Perspective", None, -1))
        self.combMethodChoice.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Median", None, -1))
        self.combMethodChoice.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Robust Mean", None, -1))
        self.combMethodChoice.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Mean", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Keep in memory", None, -1))
        self.StackTools.setItemText(self.StackTools.indexOf(self.registerTools), QtWidgets.QApplication.translate("MainWindow", "Register", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabView), QtWidgets.QApplication.translate("MainWindow", "Stack View", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Channels", None, -1))
        self.loadRedButton.setText(QtWidgets.QApplication.translate("MainWindow", "R", None, -1))
        self.loadBlueButton.setText(QtWidgets.QApplication.translate("MainWindow", "B", None, -1))
        self.loadGreenButton.setText(QtWidgets.QApplication.translate("MainWindow", "G", None, -1))
        self.loadLumButton.setText(QtWidgets.QApplication.translate("MainWindow", "L", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLRGB), QtWidgets.QApplication.translate("MainWindow", "LRGB", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Filter", None, -1))
        self.maxAvgDiamLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Max Avg Diameter", None, -1))
        self.maxAvgDiamText.setText(QtWidgets.QApplication.translate("MainWindow", "100.0", None, -1))
        self.minAvgCircLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Min Avg Circularity", None, -1))
        self.minAvgCircText.setText(QtWidgets.QApplication.translate("MainWindow", "0.0", None, -1))
        self.registrationTable.setSortingEnabled(True)
        self.registrationTable.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "# Stars", None, -1))
        self.registrationTable.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Avg Diam", None, -1))
        self.registrationTable.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Avg Circ", None, -1))
        self.registrationTable.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "X Disp", None, -1))
        self.registrationTable.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Y Disp", None, -1))
        self.registrationTable.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "Rotation", None, -1))
        self.registrationTable.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "Image File", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRegistration), QtWidgets.QApplication.translate("MainWindow", "Registration Results", None, -1))
        self.FITSMetaText.setHtml(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">FITS Header Metadata</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p></body></html>", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMetadata), QtWidgets.QApplication.translate("MainWindow", "FITS Metadata", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionSave_FITS.setText(QtWidgets.QApplication.translate("MainWindow", "Save FITS ...", None, -1))
        self.actionSave_FITS.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.actionOpen_FITS.setText(QtWidgets.QApplication.translate("MainWindow", "Open FITS ...", None, -1))
        self.actionOpen_FITS.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("MainWindow", "Close", None, -1))
        self.actionClose.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+W", None, -1))
        self.actionFindStars.setText(QtWidgets.QApplication.translate("MainWindow", "FindStars", None, -1))
        self.actionFindStars.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+F", None, -1))
        self.actionRegisterStack.setText(QtWidgets.QApplication.translate("MainWindow", "RegisterStack", None, -1))
        self.actionRegisterStack.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+R", None, -1))
        self.actionAverageStack.setText(QtWidgets.QApplication.translate("MainWindow", "AverageStack", None, -1))
        self.actionAverageStack.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+A", None, -1))
        self.actionRefIndex.setText(QtWidgets.QApplication.translate("MainWindow", "RefIndex", None, -1))
        self.actionImageIndex.setText(QtWidgets.QApplication.translate("MainWindow", "ImageIndex", None, -1))
        self.actionMaxDiam.setText(QtWidgets.QApplication.translate("MainWindow", "MaxDiam", None, -1))
        self.actionMinCirc.setText(QtWidgets.QApplication.translate("MainWindow", "MinCirc", None, -1))
        self.actionStackLevels.setText(QtWidgets.QApplication.translate("MainWindow", "StackLevels", None, -1))
        self.actionStackLevels.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Stack Intensity Levels", None, -1))

from stellate.fitsmetatext import FITSMetaText
from stellate.imageviewer import ImageViewer

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

