# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stellate.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 655)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabView = QtWidgets.QWidget()
        self.tabView.setObjectName("tabView")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabView)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.tabView)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.viewer = imgViewer(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer.sizePolicy().hasHeightForWidth())
        self.viewer.setSizePolicy(sizePolicy)
        self.viewer.setMinimumSize(QtCore.QSize(256, 256))
        self.viewer.setMaximumSize(QtCore.QSize(2560, 2560))
        self.viewer.setMouseTracking(True)
        self.viewer.setLineWidth(2)
        self.viewer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.viewer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.viewer.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.viewer.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.viewer.setObjectName("viewer")
        self.horizontalLayout.addWidget(self.viewer)
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(360, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(256, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.histogramView = PlotWidget(self.groupBox)
        self.histogramView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogramView.sizePolicy().hasHeightForWidth())
        self.histogramView.setSizePolicy(sizePolicy)
        self.histogramView.setMinimumSize(QtCore.QSize(0, 128))
        self.histogramView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.histogramView.setLineWidth(1)
        self.histogramView.setSceneRect(QtCore.QRectF(0.0, 0.0, 64.0, 64.0))
        self.histogramView.setObjectName("histogramView")
        self.gridLayout_4.addWidget(self.histogramView, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.infoGroupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoGroupBox.sizePolicy().hasHeightForWidth())
        self.infoGroupBox.setSizePolicy(sizePolicy)
        self.infoGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.infoGroupBox.setObjectName("infoGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.infoGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imageInfo = QtWidgets.QPlainTextEdit(self.infoGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageInfo.sizePolicy().hasHeightForWidth())
        self.imageInfo.setSizePolicy(sizePolicy)
        self.imageInfo.setMinimumSize(QtCore.QSize(0, 64))
        self.imageInfo.setDocumentTitle("")
        self.imageInfo.setReadOnly(True)
        self.imageInfo.setPlainText("")
        self.imageInfo.setObjectName("imageInfo")
        self.verticalLayout_2.addWidget(self.imageInfo)
        self.verticalLayout.addWidget(self.infoGroupBox)
        self.horizontalLayout.addWidget(self.widget_2)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.tabView)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.luminanceButton = QtWidgets.QPushButton(self.frame)
        self.luminanceButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.luminanceButton.sizePolicy().hasHeightForWidth())
        self.luminanceButton.setSizePolicy(sizePolicy)
        self.luminanceButton.setMinimumSize(QtCore.QSize(0, 0))
        self.luminanceButton.setCheckable(True)
        self.luminanceButton.setDefault(False)
        self.luminanceButton.setFlat(False)
        self.luminanceButton.setObjectName("luminanceButton")
        self.gridLayout.addWidget(self.luminanceButton, 1, 1, 1, 1)
        self.greenButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenButton.sizePolicy().hasHeightForWidth())
        self.greenButton.setSizePolicy(sizePolicy)
        self.greenButton.setMinimumSize(QtCore.QSize(0, 0))
        self.greenButton.setCheckable(True)
        self.greenButton.setDefault(False)
        self.greenButton.setFlat(False)
        self.greenButton.setObjectName("greenButton")
        self.gridLayout.addWidget(self.greenButton, 1, 4, 1, 1)
        self.blueButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blueButton.sizePolicy().hasHeightForWidth())
        self.blueButton.setSizePolicy(sizePolicy)
        self.blueButton.setMinimumSize(QtCore.QSize(0, 0))
        self.blueButton.setCheckable(True)
        self.blueButton.setDefault(False)
        self.blueButton.setFlat(False)
        self.blueButton.setObjectName("blueButton")
        self.gridLayout.addWidget(self.blueButton, 1, 5, 1, 1)
        self.findStarsButton = QtWidgets.QPushButton(self.frame)
        self.findStarsButton.setObjectName("findStarsButton")
        self.gridLayout.addWidget(self.findStarsButton, 0, 1, 1, 1)
        self.redButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redButton.sizePolicy().hasHeightForWidth())
        self.redButton.setSizePolicy(sizePolicy)
        self.redButton.setMinimumSize(QtCore.QSize(0, 0))
        self.redButton.setCheckable(True)
        self.redButton.setDefault(False)
        self.redButton.setFlat(False)
        self.redButton.setObjectName("redButton")
        self.gridLayout.addWidget(self.redButton, 1, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.frame)
        self.tabWidget.addTab(self.tabView, "")
        self.tabRegister = QtWidgets.QWidget()
        self.tabRegister.setObjectName("tabRegister")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabRegister)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.tabRegister)
        self.pushButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.registerImageList = QtWidgets.QTableWidget(self.tabRegister)
        self.registerImageList.setFrameShape(QtWidgets.QFrame.Panel)
        self.registerImageList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.registerImageList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.registerImageList.setAlternatingRowColors(True)
        self.registerImageList.setIconSize(QtCore.QSize(0, 0))
        self.registerImageList.setGridStyle(QtCore.Qt.DotLine)
        self.registerImageList.setWordWrap(True)
        self.registerImageList.setRowCount(20)
        self.registerImageList.setColumnCount(6)
        self.registerImageList.setObjectName("registerImageList")
        item = QtWidgets.QTableWidgetItem()
        self.registerImageList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerImageList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerImageList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerImageList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerImageList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerImageList.setHorizontalHeaderItem(5, item)
        self.registerImageList.horizontalHeader().setDefaultSectionSize(80)
        self.registerImageList.horizontalHeader().setMinimumSectionSize(64)
        self.registerImageList.horizontalHeader().setStretchLastSection(True)
        self.registerImageList.verticalHeader().setCascadingSectionResizes(False)
        self.registerImageList.verticalHeader().setDefaultSectionSize(24)
        self.registerImageList.verticalHeader().setMinimumSectionSize(20)
        self.registerImageList.verticalHeader().setSortIndicatorShown(True)
        self.registerImageList.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.registerImageList)
        self.tabWidget.addTab(self.tabRegister, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_FITS = QtWidgets.QAction(MainWindow)
        self.actionSave_FITS.setObjectName("actionSave_FITS")
        self.actionOpen_FITS = QtWidgets.QAction(MainWindow)
        self.actionOpen_FITS.setObjectName("actionOpen_FITS")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionFindStars = QtWidgets.QAction(MainWindow)
        self.actionFindStars.setObjectName("actionFindStars")
        self.menuFile.addAction(self.actionOpen_FITS)
        self.menuFile.addAction(self.actionSave_FITS)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionClose.triggered.connect(MainWindow.close)
        self.findStarsButton.clicked.connect(self.actionFindStars.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.viewer.setToolTip(_translate("MainWindow", "FITS image view. Left mouse button pans, mouse wheel zooms."))
        self.groupBox.setTitle(_translate("MainWindow", "Intensity Histogram"))
        self.infoGroupBox.setTitle(_translate("MainWindow", "Image Information"))
        self.label.setText(_translate("MainWindow", "Actions"))
        self.label_2.setText(_translate("MainWindow", "Show Channels"))
        self.luminanceButton.setText(_translate("MainWindow", "Luminance"))
        self.greenButton.setText(_translate("MainWindow", "Green"))
        self.blueButton.setText(_translate("MainWindow", "Blue"))
        self.findStarsButton.setText(_translate("MainWindow", "Find Stars"))
        self.redButton.setText(_translate("MainWindow", "Red"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabView), _translate("MainWindow", "View"))
        self.pushButton.setText(_translate("MainWindow", "Select Images to Register"))
        self.registerImageList.setSortingEnabled(True)
        item = self.registerImageList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X Disp"))
        item = self.registerImageList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y Disp"))
        item = self.registerImageList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rotation"))
        item = self.registerImageList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "# Stars"))
        item = self.registerImageList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "FWHM"))
        item = self.registerImageList.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Image File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRegister), _translate("MainWindow", "Register"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_FITS.setText(_translate("MainWindow", "Save FITS ..."))
        self.actionSave_FITS.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen_FITS.setText(_translate("MainWindow", "Open FITS ..."))
        self.actionOpen_FITS.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionFindStars.setText(_translate("MainWindow", "FindStars"))
        self.actionFindStars.setShortcut(_translate("MainWindow", "Ctrl+F"))

from stellate.imgviewer import imgViewer
from pyqtgraph import PlotWidget
