# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stellate.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 722)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 24))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 45))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.fnameText = QtWidgets.QLineEdit(self.widget)
        self.fnameText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fnameText.setReadOnly(True)
        self.fnameText.setPlaceholderText("")
        self.fnameText.setObjectName("fnameText")
        self.horizontalLayout_5.addWidget(self.fnameText)
        self.indexLabel = QtWidgets.QLabel(self.widget)
        self.indexLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.indexLabel.setObjectName("indexLabel")
        self.horizontalLayout_5.addWidget(self.indexLabel)
        self.indexText = QtWidgets.QLineEdit(self.widget)
        self.indexText.setMaximumSize(QtCore.QSize(60, 16777215))
        self.indexText.setAlignment(QtCore.Qt.AlignCenter)
        self.indexText.setReadOnly(False)
        self.indexText.setObjectName("indexText")
        self.horizontalLayout_5.addWidget(self.indexText)
        self.ofLabel = QtWidgets.QLabel(self.widget)
        self.ofLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ofLabel.setObjectName("ofLabel")
        self.horizontalLayout_5.addWidget(self.ofLabel)
        self.maxIndexText = QtWidgets.QLineEdit(self.widget)
        self.maxIndexText.setMaximumSize(QtCore.QSize(60, 16777215))
        self.maxIndexText.setFrame(False)
        self.maxIndexText.setAlignment(QtCore.Qt.AlignCenter)
        self.maxIndexText.setReadOnly(True)
        self.maxIndexText.setObjectName("maxIndexText")
        self.horizontalLayout_5.addWidget(self.maxIndexText)
        self.verticalLayout_2.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabView = QtWidgets.QWidget()
        self.tabView.setObjectName("tabView")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StackTools = QtWidgets.QToolBox(self.tabView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackTools.sizePolicy().hasHeightForWidth())
        self.StackTools.setSizePolicy(sizePolicy)
        self.StackTools.setMinimumSize(QtCore.QSize(200, 400))
        self.StackTools.setMaximumSize(QtCore.QSize(200, 16777215))
        self.StackTools.setAutoFillBackground(False)
        self.StackTools.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.StackTools.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.StackTools.setLineWidth(1)
        self.StackTools.setMidLineWidth(0)
        self.StackTools.setObjectName("StackTools")
        self.levelsTools = QtWidgets.QWidget()
        self.levelsTools.setGeometry(QtCore.QRect(0, 0, 200, 445))
        self.levelsTools.setObjectName("levelsTools")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.levelsTools)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.maxLevelSlider = QtWidgets.QSlider(self.levelsTools)
        self.maxLevelSlider.setMaximum(100)
        self.maxLevelSlider.setProperty("value", 100)
        self.maxLevelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.maxLevelSlider.setObjectName("maxLevelSlider")
        self.verticalLayout_5.addWidget(self.maxLevelSlider)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minLevelText = QtWidgets.QLineEdit(self.levelsTools)
        self.minLevelText.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.minLevelText.setAlignment(QtCore.Qt.AlignCenter)
        self.minLevelText.setObjectName("minLevelText")
        self.horizontalLayout_2.addWidget(self.minLevelText)
        self.maxLevelText = QtWidgets.QLineEdit(self.levelsTools)
        self.maxLevelText.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.maxLevelText.setAlignment(QtCore.Qt.AlignCenter)
        self.maxLevelText.setObjectName("maxLevelText")
        self.horizontalLayout_2.addWidget(self.maxLevelText)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.minLevelSlider = QtWidgets.QSlider(self.levelsTools)
        self.minLevelSlider.setMaximum(100)
        self.minLevelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minLevelSlider.setObjectName("minLevelSlider")
        self.verticalLayout_5.addWidget(self.minLevelSlider)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.StackTools.addItem(self.levelsTools, "")
        self.starsTools = QtWidgets.QWidget()
        self.starsTools.setGeometry(QtCore.QRect(0, 0, 116, 62))
        self.starsTools.setObjectName("starsTools")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.starsTools)
        self.verticalLayout.setObjectName("verticalLayout")
        self.findStarsButton = QtWidgets.QPushButton(self.starsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findStarsButton.sizePolicy().hasHeightForWidth())
        self.findStarsButton.setSizePolicy(sizePolicy)
        self.findStarsButton.setMinimumSize(QtCore.QSize(0, 40))
        self.findStarsButton.setMaximumSize(QtCore.QSize(1000, 40))
        self.findStarsButton.setObjectName("findStarsButton")
        self.verticalLayout.addWidget(self.findStarsButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 398, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.StackTools.addItem(self.starsTools, "")
        self.registerTools = QtWidgets.QWidget()
        self.registerTools.setGeometry(QtCore.QRect(0, 0, 193, 262))
        self.registerTools.setObjectName("registerTools")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.registerTools)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.registerStackButton = QtWidgets.QPushButton(self.registerTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerStackButton.sizePolicy().hasHeightForWidth())
        self.registerStackButton.setSizePolicy(sizePolicy)
        self.registerStackButton.setMinimumSize(QtCore.QSize(175, 40))
        self.registerStackButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.registerStackButton.setObjectName("registerStackButton")
        self.verticalLayout_6.addWidget(self.registerStackButton)
        self.averageStackButton = QtWidgets.QPushButton(self.registerTools)
        self.averageStackButton.setMinimumSize(QtCore.QSize(175, 40))
        self.averageStackButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.averageStackButton.setCheckable(False)
        self.averageStackButton.setObjectName("averageStackButton")
        self.verticalLayout_6.addWidget(self.averageStackButton)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.refIndexLabel = QtWidgets.QLabel(self.registerTools)
        self.refIndexLabel.setObjectName("refIndexLabel")
        self.horizontalLayout_4.addWidget(self.refIndexLabel)
        self.refIndexText = QtWidgets.QLineEdit(self.registerTools)
        self.refIndexText.setText("")
        self.refIndexText.setAlignment(QtCore.Qt.AlignCenter)
        self.refIndexText.setReadOnly(False)
        self.refIndexText.setObjectName("refIndexText")
        self.horizontalLayout_4.addWidget(self.refIndexText)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.misregModelChoice = QtWidgets.QComboBox(self.registerTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.misregModelChoice.sizePolicy().hasHeightForWidth())
        self.misregModelChoice.setSizePolicy(sizePolicy)
        self.misregModelChoice.setMinimumSize(QtCore.QSize(175, 0))
        self.misregModelChoice.setMaximumSize(QtCore.QSize(200, 16777215))
        self.misregModelChoice.setObjectName("misregModelChoice")
        self.misregModelChoice.addItem("")
        self.misregModelChoice.addItem("")
        self.misregModelChoice.addItem("")
        self.verticalLayout_6.addWidget(self.misregModelChoice)
        self.combMethodChoice = QtWidgets.QComboBox(self.registerTools)
        self.combMethodChoice.setMinimumSize(QtCore.QSize(175, 0))
        self.combMethodChoice.setMaximumSize(QtCore.QSize(200, 16777215))
        self.combMethodChoice.setObjectName("combMethodChoice")
        self.combMethodChoice.addItem("")
        self.combMethodChoice.addItem("")
        self.combMethodChoice.addItem("")
        self.verticalLayout_6.addWidget(self.combMethodChoice)
        self.checkBox = QtWidgets.QCheckBox(self.registerTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setMinimumSize(QtCore.QSize(175, 0))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(self.checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 398, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.registerProgressBar = QtWidgets.QProgressBar(self.registerTools)
        self.registerProgressBar.setProperty("value", 0)
        self.registerProgressBar.setInvertedAppearance(False)
        self.registerProgressBar.setObjectName("registerProgressBar")
        self.verticalLayout_6.addWidget(self.registerProgressBar)
        self.StackTools.addItem(self.registerTools, "")
        self.horizontalLayout.addWidget(self.StackTools)
        self.StackViewer = ImageViewer(self.tabView)
        self.StackViewer.setMinimumSize(QtCore.QSize(400, 400))
        self.StackViewer.setObjectName("StackViewer")
        self.horizontalLayout.addWidget(self.StackViewer)
        self.tabWidget.addTab(self.tabView, "")
        self.tabLRGB = QtWidgets.QWidget()
        self.tabLRGB.setObjectName("tabLRGB")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tabLRGB)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_2 = QtWidgets.QWidget(self.tabLRGB)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.loadLumButton = QtWidgets.QPushButton(self.groupBox_2)
        self.loadLumButton.setMinimumSize(QtCore.QSize(40, 40))
        self.loadLumButton.setMaximumSize(QtCore.QSize(40, 40))
        self.loadLumButton.setObjectName("loadLumButton")
        self.horizontalLayout_6.addWidget(self.loadLumButton)
        self.loadRedButton = QtWidgets.QPushButton(self.groupBox_2)
        self.loadRedButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loadRedButton.setMaximumSize(QtCore.QSize(40, 40))
        self.loadRedButton.setObjectName("loadRedButton")
        self.horizontalLayout_6.addWidget(self.loadRedButton)
        self.loadGreenButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadGreenButton.sizePolicy().hasHeightForWidth())
        self.loadGreenButton.setSizePolicy(sizePolicy)
        self.loadGreenButton.setMinimumSize(QtCore.QSize(40, 40))
        self.loadGreenButton.setMaximumSize(QtCore.QSize(40, 40))
        self.loadGreenButton.setObjectName("loadGreenButton")
        self.horizontalLayout_6.addWidget(self.loadGreenButton)
        self.loadBlueButton = QtWidgets.QPushButton(self.groupBox_2)
        self.loadBlueButton.setMinimumSize(QtCore.QSize(40, 40))
        self.loadBlueButton.setMaximumSize(QtCore.QSize(40, 40))
        self.loadBlueButton.setObjectName("loadBlueButton")
        self.horizontalLayout_6.addWidget(self.loadBlueButton)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lumSlider = QtWidgets.QSlider(self.groupBox_4)
        self.lumSlider.setMaximum(100)
        self.lumSlider.setProperty("value", 100)
        self.lumSlider.setOrientation(QtCore.Qt.Vertical)
        self.lumSlider.setObjectName("lumSlider")
        self.horizontalLayout_9.addWidget(self.lumSlider)
        self.redSlider = QtWidgets.QSlider(self.groupBox_4)
        self.redSlider.setMaximum(100)
        self.redSlider.setProperty("value", 100)
        self.redSlider.setOrientation(QtCore.Qt.Vertical)
        self.redSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.redSlider.setTickInterval(25)
        self.redSlider.setObjectName("redSlider")
        self.horizontalLayout_9.addWidget(self.redSlider)
        self.greenSlider = QtWidgets.QSlider(self.groupBox_4)
        self.greenSlider.setMaximum(100)
        self.greenSlider.setProperty("value", 100)
        self.greenSlider.setOrientation(QtCore.Qt.Vertical)
        self.greenSlider.setObjectName("greenSlider")
        self.horizontalLayout_9.addWidget(self.greenSlider)
        self.blueSlider = QtWidgets.QSlider(self.groupBox_4)
        self.blueSlider.setMaximum(100)
        self.blueSlider.setProperty("value", 100)
        self.blueSlider.setOrientation(QtCore.Qt.Vertical)
        self.blueSlider.setObjectName("blueSlider")
        self.horizontalLayout_9.addWidget(self.blueSlider)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_8.addWidget(self.widget_2)
        self.LRGBViewer = ImageViewer(self.tabLRGB)
        self.LRGBViewer.setMinimumSize(QtCore.QSize(400, 400))
        self.LRGBViewer.setObjectName("LRGBViewer")
        self.horizontalLayout_8.addWidget(self.LRGBViewer)
        self.tabWidget.addTab(self.tabLRGB, "")
        self.tabRegistration = QtWidgets.QWidget()
        self.tabRegistration.setObjectName("tabRegistration")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabRegistration)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tabRegistration)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(4, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.maxAvgDiamLabel = QtWidgets.QLabel(self.groupBox)
        self.maxAvgDiamLabel.setObjectName("maxAvgDiamLabel")
        self.horizontalLayout_3.addWidget(self.maxAvgDiamLabel)
        self.maxAvgDiamText = QtWidgets.QLineEdit(self.groupBox)
        self.maxAvgDiamText.setMaximumSize(QtCore.QSize(75, 16777215))
        self.maxAvgDiamText.setAlignment(QtCore.Qt.AlignCenter)
        self.maxAvgDiamText.setObjectName("maxAvgDiamText")
        self.horizontalLayout_3.addWidget(self.maxAvgDiamText)
        self.minAvgCircLabel = QtWidgets.QLabel(self.groupBox)
        self.minAvgCircLabel.setObjectName("minAvgCircLabel")
        self.horizontalLayout_3.addWidget(self.minAvgCircLabel)
        self.minAvgCircText = QtWidgets.QLineEdit(self.groupBox)
        self.minAvgCircText.setMaximumSize(QtCore.QSize(75, 16777215))
        self.minAvgCircText.setAlignment(QtCore.Qt.AlignCenter)
        self.minAvgCircText.setObjectName("minAvgCircText")
        self.horizontalLayout_3.addWidget(self.minAvgCircText)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.registrationTable = QtWidgets.QTableWidget(self.tabRegistration)
        self.registrationTable.setFrameShape(QtWidgets.QFrame.Panel)
        self.registrationTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.registrationTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.registrationTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.registrationTable.setAlternatingRowColors(False)
        self.registrationTable.setIconSize(QtCore.QSize(0, 0))
        self.registrationTable.setGridStyle(QtCore.Qt.DotLine)
        self.registrationTable.setWordWrap(True)
        self.registrationTable.setRowCount(0)
        self.registrationTable.setColumnCount(7)
        self.registrationTable.setObjectName("registrationTable")
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.registrationTable.setHorizontalHeaderItem(6, item)
        self.registrationTable.horizontalHeader().setDefaultSectionSize(80)
        self.registrationTable.horizontalHeader().setMinimumSectionSize(64)
        self.registrationTable.horizontalHeader().setStretchLastSection(True)
        self.registrationTable.verticalHeader().setCascadingSectionResizes(False)
        self.registrationTable.verticalHeader().setDefaultSectionSize(24)
        self.registrationTable.verticalHeader().setMinimumSectionSize(20)
        self.registrationTable.verticalHeader().setSortIndicatorShown(True)
        self.registrationTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.registrationTable)
        self.tabWidget.addTab(self.tabRegistration, "")
        self.tabMetadata = QtWidgets.QWidget()
        self.tabMetadata.setObjectName("tabMetadata")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabMetadata)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.FITSMetaText = FITSMetaText(self.tabMetadata)
        self.FITSMetaText.setObjectName("FITSMetaText")
        self.verticalLayout_7.addWidget(self.FITSMetaText)
        self.tabWidget.addTab(self.tabMetadata, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_FITS = QtWidgets.QAction(MainWindow)
        self.actionSave_FITS.setObjectName("actionSave_FITS")
        self.actionOpen_FITS = QtWidgets.QAction(MainWindow)
        self.actionOpen_FITS.setObjectName("actionOpen_FITS")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionFindStars = QtWidgets.QAction(MainWindow)
        self.actionFindStars.setObjectName("actionFindStars")
        self.actionRegisterStack = QtWidgets.QAction(MainWindow)
        self.actionRegisterStack.setObjectName("actionRegisterStack")
        self.actionAverageStack = QtWidgets.QAction(MainWindow)
        self.actionAverageStack.setObjectName("actionAverageStack")
        self.actionRefIndex = QtWidgets.QAction(MainWindow)
        self.actionRefIndex.setObjectName("actionRefIndex")
        self.actionImageIndex = QtWidgets.QAction(MainWindow)
        self.actionImageIndex.setObjectName("actionImageIndex")
        self.actionMaxDiam = QtWidgets.QAction(MainWindow)
        self.actionMaxDiam.setObjectName("actionMaxDiam")
        self.actionMinCirc = QtWidgets.QAction(MainWindow)
        self.actionMinCirc.setObjectName("actionMinCirc")
        self.actionStackLevels = QtWidgets.QAction(MainWindow)
        self.actionStackLevels.setObjectName("actionStackLevels")
        self.menuFile.addAction(self.actionOpen_FITS)
        self.menuFile.addAction(self.actionSave_FITS)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.StackTools.setCurrentIndex(0)
        self.misregModelChoice.setCurrentIndex(1)
        self.combMethodChoice.setCurrentIndex(0)
        self.actionClose.triggered.connect(MainWindow.close)
        self.indexText.returnPressed.connect(self.actionImageIndex.trigger)
        self.maxAvgDiamText.returnPressed.connect(self.actionMaxDiam.trigger)
        self.minAvgCircText.returnPressed.connect(self.actionMinCirc.trigger)
        self.registerStackButton.clicked.connect(self.actionRegisterStack.trigger)
        self.averageStackButton.clicked.connect(self.actionAverageStack.trigger)
        self.findStarsButton.clicked.connect(self.actionFindStars.trigger)
        self.refIndexText.returnPressed.connect(self.actionRefIndex.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Image File"))
        self.fnameText.setText(_translate("MainWindow", "No Image Loaded"))
        self.indexLabel.setText(_translate("MainWindow", "Index"))
        self.indexText.setText(_translate("MainWindow", "0"))
        self.ofLabel.setText(_translate("MainWindow", "of"))
        self.maxIndexText.setText(_translate("MainWindow", "0"))
        self.minLevelText.setText(_translate("MainWindow", "0"))
        self.maxLevelText.setText(_translate("MainWindow", "100"))
        self.StackTools.setItemText(self.StackTools.indexOf(self.levelsTools), _translate("MainWindow", "Levels"))
        self.findStarsButton.setText(_translate("MainWindow", "Find Stars"))
        self.StackTools.setItemText(self.StackTools.indexOf(self.starsTools), _translate("MainWindow", "Stars"))
        self.registerStackButton.setText(_translate("MainWindow", "Register Stack"))
        self.averageStackButton.setText(_translate("MainWindow", "Combine Stack"))
        self.refIndexLabel.setText(_translate("MainWindow", "Reference Index"))
        self.misregModelChoice.setItemText(0, _translate("MainWindow", "Rigid Body"))
        self.misregModelChoice.setItemText(1, _translate("MainWindow", "Affine"))
        self.misregModelChoice.setItemText(2, _translate("MainWindow", "Perspective"))
        self.combMethodChoice.setItemText(0, _translate("MainWindow", "Median"))
        self.combMethodChoice.setItemText(1, _translate("MainWindow", "Robust Mean"))
        self.combMethodChoice.setItemText(2, _translate("MainWindow", "Mean"))
        self.checkBox.setText(_translate("MainWindow", "Keep in memory"))
        self.StackTools.setItemText(self.StackTools.indexOf(self.registerTools), _translate("MainWindow", "Register"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabView), _translate("MainWindow", "Stack View"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Load"))
        self.loadLumButton.setText(_translate("MainWindow", "L"))
        self.loadRedButton.setText(_translate("MainWindow", "R"))
        self.loadGreenButton.setText(_translate("MainWindow", "G"))
        self.loadBlueButton.setText(_translate("MainWindow", "B"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Mixer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLRGB), _translate("MainWindow", "LRGB"))
        self.groupBox.setTitle(_translate("MainWindow", "Filter"))
        self.maxAvgDiamLabel.setText(_translate("MainWindow", "Max Avg Diameter"))
        self.maxAvgDiamText.setText(_translate("MainWindow", "100.0"))
        self.minAvgCircLabel.setText(_translate("MainWindow", "Min Avg Circularity"))
        self.minAvgCircText.setText(_translate("MainWindow", "0.0"))
        self.registrationTable.setSortingEnabled(True)
        item = self.registrationTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "# Stars"))
        item = self.registrationTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Avg Diam"))
        item = self.registrationTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Avg Circ"))
        item = self.registrationTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "X Disp"))
        item = self.registrationTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Y Disp"))
        item = self.registrationTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Rotation"))
        item = self.registrationTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Image File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRegistration), _translate("MainWindow", "Registration Results"))
        self.FITSMetaText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">FITS Header Metadata</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMetadata), _translate("MainWindow", "FITS Metadata"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_FITS.setText(_translate("MainWindow", "Save FITS ..."))
        self.actionSave_FITS.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen_FITS.setText(_translate("MainWindow", "Open FITS ..."))
        self.actionOpen_FITS.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionFindStars.setText(_translate("MainWindow", "FindStars"))
        self.actionFindStars.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionRegisterStack.setText(_translate("MainWindow", "RegisterStack"))
        self.actionRegisterStack.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionAverageStack.setText(_translate("MainWindow", "AverageStack"))
        self.actionAverageStack.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionRefIndex.setText(_translate("MainWindow", "RefIndex"))
        self.actionImageIndex.setText(_translate("MainWindow", "ImageIndex"))
        self.actionMaxDiam.setText(_translate("MainWindow", "MaxDiam"))
        self.actionMinCirc.setText(_translate("MainWindow", "MinCirc"))
        self.actionStackLevels.setText(_translate("MainWindow", "StackLevels"))
        self.actionStackLevels.setToolTip(_translate("MainWindow", "Stack Intensity Levels"))

from stellate.fitsmetatext import FITSMetaText
from stellate.imageviewer import ImageViewer
